import express from 'express';
import { get_sales, get_total_sales, get_total_orders, get_total_orders_by_company, get_average_order, get_total_margin, get_margin_percent, get_delivery_full, get_sales_trend, get_top_customers, get_number_of_customers, get_discount_given, get_top_products, get_top_brands, get_sales_person, get_sales_stats, first_last_date, get_companies, get_company_stats, get_sales_report_yoy, get_sales_report_mom, get_sales_report_mtd, get_sales_report_ytd, get_company_sales_stats, get_top_category, get_active_customers, get_invoice_progress, get_order_fullfilment, get_sales_stats_ytd, get_company_orders } from '../controllers/salesController.js';

const router = express.Router();
router.get('/master', get_sales);
router.get('/total_sales', get_total_sales);
router.get('/company_orders', get_company_orders);
router.get('/total_orders', get_total_orders);
router.get('/active_customer', get_active_customers);
router.get('/invoice_progress', get_invoice_progress);
router.get('/total_orders_by_company', get_total_orders_by_company);
router.get('/average_orders', get_average_order);
router.get('/total_margin', get_total_margin);
router.get('/margin_percent', get_margin_percent);
router.get('/delivery_full', get_delivery_full);
router.get('/get_sales_trend', get_sales_trend);
router.get('/company_stats', get_company_stats);
router.get('/report_yoy', get_sales_report_yoy);
router.get('/report_mom', get_sales_report_mom);
router.get('/report_mtd', get_sales_report_mtd);
router.get('/stats_ytd', get_sales_stats_ytd);
router.get('/report_ytd', get_sales_report_ytd);
router.get('/top_category', get_top_category);
router.get('/get_top_customers', get_top_customers);
router.get('/number_of_customers', get_number_of_customers);
router.get('/discount_given', get_discount_given);
router.get('/top_products', get_top_products);
router.get('/top_brands', get_top_brands);
router.get('/get_sales_person', get_sales_person);
router.get('/get_sales_stats', get_sales_stats);
router.get('/get_company_sales_stats', get_company_sales_stats);
router.get('/order_fullfilment', get_order_fullfilment);
router.get('/first_last_date', first_last_date);
router.get('/companies', get_companies);

export default router;